### ISSUE TITLE
Not working with Java 9

### ISSUE THREAD

**Issue by Mc128k** [brunchboy/beat-link-trigger#31] opened 2017-09-29 14:51 UTC
Using Java 9 on OSX 10.12.6 results in the application crashing at startup.

**Comment by brunchboy** [comment] 2017-09-29 15:23
I’m not surprised to hear this, but there are no plans as yet to try to work with Java 9. They can’t even be started until all of the dependencies (including native code ones) are ported to Java 9. For the foreseeable future, use BLT with Java 8.

**Comment by brunchboy** [comment] 2017-09-29 15:25
I will update the read me to make this clear when I have some time back at an appropriate computer, though. Thanks for the report!

**Comment by brunchboy** [comment] 2017-10-02 03:27
All right, I have updated the project page to let people know they should use Java 8. If anyone wants to work on helping our transitive dependencies get themselves updated to support Java 9, and then submit a pull request here to update to those versions once you have confirmed that they now work, that would be welcome!

**Comment by brunchboy** [comment] 2018-06-18 03:37
I’ve started working on this. It looks like the worst problem is in the Substance look-and-feel package which gives us the nice dark UI. And that is no longer maintained. So I have created a branch where I am fixing other issues, and looking for a replacement that looks at least decent. I expect this will be a version 0.4.0 release which requires at least Java 9 and is compatible with Java 10 once I am finished.

**Comment by brunchboy** [comment] 2018-06-22 05:27
There is a now preview release that works in Java 9 and 10, if you would like to try it, @Mc128k

**Comment by Mc128k** [comment] 2018-06-29 22:10
I can try this in a few months, please feel free to close the issue if you wish

**Comment by brunchboy** [comment] 2018-06-30 17:45
Thanks, I’ll probably close it whenever I feel enough people have tested 0.4.0 to release it.

**Comment by brunchboy** [comment] 2018-09-22 03:46
The latest preview release of 0.4.0 restores the Lucida Sans font that the Beat Link Trigger UI was designed around even under Java 9 and later on the Mac. As discussed in https://github.com/kirill-grouchnikov/radiance/issues/6#issuecomment-423548892, Radiance is scheduled for release the week of October 8, so I am aiming for my own release shortly after that. I’m starting to revise the user guide to accommodate all the other features that have made it into 0.4.0 this weekend.

**Comment by brunchboy** [comment] 2018-10-13 22:49
This was resolved with the release of 0.4.0 🎉

**Closed by brunchboy** 2018-10-13 22:49 UTC
Labels: enhancement
